# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testbase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study_group',
            name='course_leader',
        ),
        migrations.AlterField(
            model_name='student',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testbase.Study_Group'),
        ),
    ]
