# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testbase', '0006_auto_20180305_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='in_group',
            new_name='off_group',
        ),
    ]
