# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testbase', '0007_auto_20180305_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=254, verbose_name='name of model')),
                ('model_create', models.CharField(max_length=255, verbose_name='Info about model creation')),
                ('model_editing', models.CharField(max_length=255, verbose_name='Info about model editing')),
                ('model_delete', models.CharField(max_length=255, verbose_name='Info about model deleting')),
            ],
        ),
    ]
