# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testbase', '0008_model_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_log',
            name='model_create',
            field=models.DateField(blank=True, null=True, verbose_name='Info about model creation'),
        ),
        migrations.AlterField(
            model_name='model_log',
            name='model_delete',
            field=models.DateField(blank=True, null=True, verbose_name='Info about model deleting'),
        ),
        migrations.AlterField(
            model_name='model_log',
            name='model_editing',
            field=models.DateField(blank=True, null=True, verbose_name='Info about model editing'),
        ),
    ]
