# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testbase', '0009_auto_20180306_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model_log',
            old_name='model_editing',
            new_name='model_edit',
        ),
    ]
