# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-25 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testbase', '0013_auto_20180308_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='off_group',
        ),
        migrations.AddField(
            model_name='student',
            name='in_group',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='testbase.Group'),
        ),
    ]
